module.exports = {
  NEW_PROJECT_CREATED: 'project/NEW_PROJECT_CREATED',
  NEW_TASK_CREATED: 'task/NEW_TASK_CREATED',
  TASK_STATE_CHANGED: 'task/TASK_STATE_CHANGED',
  FORM_VALIDATION_ERROR: 'form/VALIDATION_ERROR',
  ACCESS_DENIED: 'user/ACCESS_DENIED'
}
